Repository PasteUs/PasteMeFrontend, pull requests merged in 2020-02, with the labels that each got.

#188 Change path
  public/conf.d/docker/nginx.conf
  public/conf.d/nginx.conf
  public/usr/config.example.json
Labels: enhancement

#190 announcement
  package-lock.json
  package.json
  public/usr/config.example.json
  src/components/Form.vue
  src/components/Header.vue
  src/components/PasswordAuth.vue
  src/main.js
  src/views/Index.vue
  vue.config.js
Labels: enhancement

#191 Bugfix/fix package lock
  package-lock.json
Labels: bug

#192 accouncement_fixBug
  src/components/Header.vue
  src/components/icons/Bell.vue
Labels: bug

#193 announcement_fixBug
  src/components/Header.vue
Labels: bug

#194 Update README.md
  README.md
Labels: documentation

#195 announcement_fixBug
  src/components/Header.vue
Labels: bug

#197 announcement_fixBug
  public/usr/config.example.json
  src/assets/lang/en.js
Labels: bug

#196 announcement
  .drone.yml
  .github/release-drafter.yml
  .github/shell/build_and_update_cdn.sh
  .github/shell/pasteme_dev_update.sh
  .github/workflows/dev.yml
  .github/workflows/master.yml
  .github/workflows/nodejs.yml
  .github/workflows/release-drafter.yml
  .github/workflows/upload-to-release.yml
  .travis.yml
  Dockerfile
  README.md
  dev.Dockerfile
  installer.sh
  package-lock.json
  package.json
  public/conf.d/docker/nginx.conf
  public/conf.d/nginx.conf
  public/usr/config.example.json
  shell/dev.sh
  shell/dist/master.sh
  shell/master.sh
  src/assets/js/highlightjs-line-numbers.js
  src/assets/js/router.js
  src/assets/lang/en.js
  src/assets/lang/zh-CN.js
  src/components/Form.vue
  src/components/Header.vue
  src/components/PasswordAuth.vue
  src/components/icons/Bell.vue
  src/main.js
  src/views/Index.vue
  vue.config.js
Labels: enhancement

#205 Update release-drafter's version
  .github/workflows/release-drafter.yml
Labels: bug

#206 Fix release drafter
  .github/workflows/release-drafter.yml
Labels: bug
